// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestFull.Migrations;

#nullable disable

namespace RestFull.Migrations
{
    [DbContext(typeof(SetDbContext))]
    partial class SetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.14");

            modelBuilder.Entity("RestFull.Models.Order", b =>
                {
                    b.Property<int>("idMain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmountOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameOrder")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("idMain");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            idMain = 1,
                            AmountOrder = 2,
                            ID = "0f8fad5b-d9cb-469f-a165-70867728950e",
                            NameOrder = "Blade"
                        });
                });

            modelBuilder.Entity("RestFull.Models.ServiceObject", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("serviceObjects");

                    b.HasData(
                        new
                        {
                            ID = "0f8fad5b-d9cb-469f-a165-70867728950e",
                            Amount = 15,
                            Name = "Blade"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
